# Generated by Django 6.1.1 on 2026-09-24 05:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(choices=[('new', 'New'), ('asking', 'Asking'), ('ai_chat', 'Ai Chat'), ('diagnosed', 'Diagnosed')], default='new', max_length=20)),
                ('current_issue', models.CharField(blank=True, max_length=50)),
                ('question_index', models.PositiveSmallIntegerField(default=0)),
                ('answers', models.JSONField(blank=True, default=list)),
                ('ai_turns', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('recommendation', models.TextField()),
                ('service', models.CharField(max_length=100)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('estimated_cost', models.CharField(blank=True, max_length=60)),
                ('source', models.CharField(choices=[('rule', 'Rule'), ('ai', 'Ai')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='chat.conversation')),
            ],
            options={
                'verbose_name_plural': 'diagnoses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{10,13}$', 'Enter a valid phone number (10 to 13 digits).')])),
                ('car_model', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('preferred_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('morning', 'Morning (9 AM - 12 PM)'), ('afternoon', 'Afternoon (12 PM - 4 PM)'), ('evening', 'Evening (4 PM - 7 PM)')], max_length=10)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='chat.conversation')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='chat.diagnosis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('source', models.CharField(choices=[('user', 'User'), ('rule', 'Rule'), ('ai', 'Ai')], default='user', max_length=10)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='chat.message')),
            ],
        ),
    ]
